### ISSUE TITLE
File and system setup?

### ISSUE THREAD

**Issue by ghost** [ACJZA/CSeries#2]
Hi, 
for testing reasons, I'd like to set up a working systems and file setup, so I'd like to ask you what you think of using using the CRJ700-family as a base for the systems?
Regards
D-ECHO

**Comment by ACJZA** [comment]
Sure, was planning to get a testing base soon. Also itouch suggests using Slack for communication

**Comment by ghost** [comment]
How to log into slack? :D

**Comment by ACJZA** [comment]
I'll message you when I wake up. 3AM :)

**Comment by ghost** [comment]
Ok :) have a good night

**Comment by ACJZA** [comment]
Just need your email

**Comment by D-ECHO** [comment]
Echoair at T-Online .de

**Comment by ghost** [comment]
And could you btw upload the. Blend files?

**Comment by ACJZA** [comment]
Which blend files?

**Comment by ghost** [comment]
Oh i just saw that you are using AC 3d because the thing is that I can't 
open the. ac files:'(

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: ACJZA
Betreff: Re: [ACJZA/CSeries] File and system setup? (#2)
Datum: 20.06.2016, 0:49 Uhr
An: ACJZA/CSeries
Cc: D-ECHO, Author

Which blend files?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/ACJZA/CSeries/issues/2#issuecomment-227025192 , or 
mute the thread
https://github.com/notifications/unsubscribe/ALtQ-H3QH6qkU8e4VxjwlfVRQQ_3ZaUFks5qNcdfgaJpZM4I5H2u 
.
